### ISSUE TITLE
DHT rmarkdown unaccessible 

### ISSUE THREAD

**Issue by Justice-Lu** [rhart604/mousify#1]
To whom this may concern, 

I'm currently interested in integrating both my scSeq runs of human and mice samples. And I came across your publication Ronald P. Hart 2019. I am hoping to understand your methodology in implementing similar things. However I am having hard time accessing the DHT.html file. When opened, it's just a bunch of scrambled code, only thing that is readable is the session info. 

If you have any idea, please advise. 

Thanks!

**Comment by rhart604** [comment]
It's weird but on github you need to load html like this:
https://htmlpreview.github.io?https://github.com/rhart604/mousify/blob/master/DHT.html
